language: go

go:
  - 1.5
  - tip

env:
  - GO15VENDOREXPERIMENT=1

install: true

script:
  - "go install ./apps/phosphor"
  - "go install ./apps/phosphord"
  - "go test $(go list ./... | grep -v /vendor/)"
